# Use Python 3.13
FROM python:3.13

# Set the working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir --force-reinstall -r requirements.txt

# Expose the port Render uses
EXPOSE $PORT

# Start Daphne (or Gunicorn)
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "Project.asgi:application"]
