# Generated by Django 5.1.6 on 2025-03-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0004_alter_customuser_email_alter_customuser_google_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
