# Generated by Django 5.1.6 on 2025-03-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0009_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
