# Generated by Django 5.1.6 on 2025-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0011_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
